[build]
  publish = "public"
  command = "echo 'No build step needed - using static files'"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' https://cdn.solodex.org; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.solodex.org; style-src 'self' 'unsafe-inline' https://cdn.solodex.org; img-src 'self' data: https://*;"

[[redirects]]
  from = "/api/*"
  to = "https://tradingaiguru.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
